export const FETCH_REGISTER_USER_SUCCESS = 'FETCH_REGISTER_USER_SUCCESS';
export const FETCH_REGISTER_USER_FAIL = 'FETCH_REGISTER_USER_FAIL';

export const FETCH_LOGIN_USER_SUCCESS = 'FETCH_LOGIN_USER_SUCCESS';
export const FETCH_LOGIN_USER_FAIL = 'FETCH_LOGIN_USER_FAIL';

export const FETCH_REFRESH_USER_SUCCESS = 'FETCH_REFRESH_USER_SUCCESS';
export const FETCH_REFRESH_USER_FAIL = 'FETCH_REFRESH_USER_FAIL';
